const searchSuggestions = [
  { id: 1, suggestion: "How to learn JavaScript" },
  { id: 2, suggestion: "Best programming languages in 2023" },
  { id: 3, suggestion: "Top 10 coding bootcamps" },
  { id: 4, suggestion: "What is TypeScript" },
  { id: 5, suggestion: "How to build a website" },
  { id: 6, suggestion: "Learn React step by step" },
  { id: 7, suggestion: "What is Node.js used for" },
  { id: 8, suggestion: "Best IDEs for developers" },
  { id: 9, suggestion: "How to use GitHub" },
  { id: 10, suggestion: "What is cloud computing" },
  { id: 11, suggestion: "Top 10 VS Code extensions" },
  { id: 12, suggestion: "How to deploy a web app" },
  { id: 13, suggestion: "What is Docker" },
  { id: 14, suggestion: "Learn Python for beginners" },
  { id: 15, suggestion: "How to write clean code" },
  { id: 16, suggestion: "What is machine learning" },
  { id: 17, suggestion: "Best resources to learn coding" },
  { id: 18, suggestion: "How to use APIs in JavaScript" },
  { id: 19, suggestion: "What is GraphQL" },
  { id: 20, suggestion: "How to optimize website performance" },
  { id: 21, suggestion: "What is artificial intelligence" },
  { id: 22, suggestion: "Learn CSS animations" },
  { id: 23, suggestion: "How to use Firebase" },
  { id: 24, suggestion: "What is serverless architecture" },
  { id: 25, suggestion: "How to create a portfolio website" },
  { id: 26, suggestion: "What is REST API" },
  { id: 27, suggestion: "Learn SQL for beginners" },
  { id: 28, suggestion: "How to debug JavaScript code" },
  { id: 29, suggestion: "What is Agile methodology" },
  { id: 30, suggestion: "Top 10 programming books" },
  { id: 31, suggestion: "How to use Redux in React" },
  { id: 32, suggestion: "What is WebAssembly" },
  { id: 33, suggestion: "Learn HTML5 basics" },
  { id: 34, suggestion: "How to use Tailwind CSS" },
  { id: 35, suggestion: "What is Kubernetes" },
  { id: 36, suggestion: "How to create a chatbot" },
  { id: 37, suggestion: "What is blockchain technology" },
  { id: 38, suggestion: "Learn data structures and algorithms" },
  { id: 39, suggestion: "How to use Next.js" },
  { id: 40, suggestion: "What is a progressive web app" },
  { id: 41, suggestion: "How to use MongoDB" },
  { id: 42, suggestion: "What is DevOps" },
  { id: 43, suggestion: "Learn Java for beginners" },
  { id: 44, suggestion: "How to use GraphQL with React" },
  { id: 45, suggestion: "What is a microservice architecture" },
  { id: 46, suggestion: "How to use AWS for hosting" },
  { id: 47, suggestion: "What is a virtual machine" },
  { id: 48, suggestion: "Learn PHP for web development" },
  { id: 49, suggestion: "How to use Webpack" },
  { id: 50, suggestion: "What is a CDN" },
  { id: 51, suggestion: "How to learn Swift programming" },
  { id: 52, suggestion: "What is a design pattern in programming" },
  { id: 53, suggestion: "How to use Docker Compose" },
  { id: 54, suggestion: "Learn Ruby on Rails basics" },
  { id: 55, suggestion: "What is functional programming" },
  { id: 56, suggestion: "How to use Vue.js" },
  { id: 57, suggestion: "What is a NoSQL database" },
  { id: 58, suggestion: "Learn Kotlin for Android development" },
  { id: 59, suggestion: "How to use Elasticsearch" },
  { id: 60, suggestion: "What is a web server" },
  { id: 61, suggestion: "How to use TypeORM" },
  { id: 62, suggestion: "Learn Go programming basics" },
  { id: 63, suggestion: "What is a load balancer" },
  { id: 64, suggestion: "How to use RabbitMQ" },
  { id: 65, suggestion: "What is a data warehouse" },
  { id: 66, suggestion: "Learn Scala for data processing" },
  { id: 67, suggestion: "How to use Jenkins for CI/CD" },
  { id: 68, suggestion: "What is a distributed system" },
  { id: 69, suggestion: "How to use Ansible" },
  { id: 70, suggestion: "Learn Rust programming basics" },
  { id: 71, suggestion: "What is a container orchestration tool" },
  { id: 72, suggestion: "How to use Terraform" },
  { id: 73, suggestion: "What is a message queue" },
  { id: 74, suggestion: "Learn C# for game development" },
  { id: 75, suggestion: "How to use Apache Kafka" },
  { id: 76, suggestion: "What is a relational database" },
  { id: 77, suggestion: "How to use Postman for API testing" },
  { id: 78, suggestion: "Learn Dart for Flutter development" },
  { id: 79, suggestion: "What is a monolithic architecture" },
  { id: 80, suggestion: "How to use Prometheus for monitoring" },
  { id: 81, suggestion: "What is a reverse proxy" },
  { id: 82, suggestion: "Learn MATLAB for data analysis" },
  { id: 83, suggestion: "How to use Apache Spark" },
  { id: 84, suggestion: "What is a hybrid cloud" },
  { id: 85, suggestion: "How to use OpenShift" },
  { id: 86, suggestion: "Learn Perl for scripting" },
  { id: 87, suggestion: "What is a content management system" },
  { id: 88, suggestion: "How to use Nginx" },
  { id: 89, suggestion: "What is a web application firewall" },
  { id: 90, suggestion: "Learn Haskell for functional programming" },
  { id: 91, suggestion: "How to use Redis for caching" },
  { id: 92, suggestion: "What is a cloud-native application" },
  { id: 93, suggestion: "How to use GraphQL subscriptions" },
  { id: 94, suggestion: "Learn Objective-C for iOS development" },
  { id: 95, suggestion: "What is a blockchain consensus algorithm" },
  { id: 96, suggestion: "How to use Selenium for testing" },
  { id: 97, suggestion: "What is a microfrontend architecture" },
  { id: 98, suggestion: "Learn Julia for scientific computing" },
  { id: 99, suggestion: "How to use Apache Hadoop" },
  { id: 100, suggestion: "What is a server-side rendering" },
  { id: 101, suggestion: "How to use Kubernetes for deployment" },
  { id: 102, suggestion: "What is a neural network" },
  { id: 103, suggestion: "How to use Flask for web development" },
  { id: 104, suggestion: "Learn R programming for data science" },
  { id: 105, suggestion: "What is a software development lifecycle" },
  { id: 106, suggestion: "How to use Apache Cassandra" },
  { id: 107, suggestion: "What is a real-time database" },
  { id: 108, suggestion: "Learn Solidity for blockchain development" },
  { id: 109, suggestion: "How to use Apache Airflow" },
  { id: 110, suggestion: "What is a cloud service provider" },
  { id: 111, suggestion: "How to use Spring Boot for Java development" },
  { id: 112, suggestion: "Learn COBOL for legacy systems" },
  { id: 113, suggestion: "What is a web socket" },
  { id: 114, suggestion: "How to use TensorFlow for machine learning" },
  { id: 115, suggestion: "What is a data lake" },
  { id: 116, suggestion: "Learn Bash scripting for automation" },
  { id: 117, suggestion: "How to use PyTorch for deep learning" },
  { id: 118, suggestion: "What is a software architecture pattern" },
  { id: 119, suggestion: "How to use Apache ZooKeeper" },
  { id: 120, suggestion: "Learn Erlang for distributed systems" },
  { id: 121, suggestion: "What is a web crawler" },
  { id: 122, suggestion: "How to use GraphQL with Apollo" },
  { id: 123, suggestion: "What is a software testing lifecycle" },
  { id: 124, suggestion: "Learn Fortran for scientific computing" },
  { id: 125, suggestion: "How to use OpenCV for image processing" },
  { id: 126, suggestion: "What is a software container" },
  { id: 127, suggestion: "How to use gRPC for communication" },
  { id: 128, suggestion: "Learn Groovy for scripting" },
  { id: 129, suggestion: "What is a software dependency" },
  { id: 130, suggestion: "How to use Apache Beam for data processing" },
  { id: 131, suggestion: "What is a software design principle" },
  { id: 132, suggestion: "Learn OCaml for functional programming" },
  { id: 133, suggestion: "How to use Jupyter Notebooks" },
  { id: 134, suggestion: "What is a software build tool" },
  { id: 135, suggestion: "How to use Apache Mesos" },
  { id: 136, suggestion: "Learn Crystal programming basics" },
  { id: 137, suggestion: "What is a software integration test" },
  { id: 138, suggestion: "How to use Apache Flink" },
  { id: 139, suggestion: "What is a software deployment pipeline" },
  { id: 140, suggestion: "Learn Nim programming basics" },
  { id: 141, suggestion: "How to use Apache Storm" },
  { id: 142, suggestion: "What is a software configuration management" },
  { id: 143, suggestion: "How to use Apache Solr" },
  { id: 144, suggestion: "Learn F# for functional programming" },
  { id: 145, suggestion: "What is a software quality assurance" },
  { id: 146, suggestion: "How to use Apache Camel" },
  { id: 147, suggestion: "What is a software release management" },
  { id: 148, suggestion: "Learn V programming basics" },
  { id: 149, suggestion: "How to use Apache Ignite" },
  { id: 150, suggestion: "What is a software performance test" },
  { id: 151, suggestion: "How to use Apache HBase" },
  { id: 152, suggestion: "Learn Ada programming basics" },
  { id: 153, suggestion: "What is a software usability test" },
  { id: 154, suggestion: "How to use Apache NiFi" },
  { id: 155, suggestion: "What is a software scalability test" },
  { id: 156, suggestion: "Learn D programming basics" },
  { id: 157, suggestion: "How to use Apache Drill" },
  { id: 158, suggestion: "What is a software maintainability test" },
  { id: 159, suggestion: "How to use Apache Kafka Streams" },
  { id: 160, suggestion: "Learn Zig programming basics" },
  { id: 161, suggestion: "What is a software reliability test" },
  { id: 162, suggestion: "How to use Apache Arrow" },
  { id: 163, suggestion: "What is a software compatibility test" },
  { id: 164, suggestion: "Learn Elixir for concurrent programming" },
  { id: 165, suggestion: "How to use Apache Parquet" },
  { id: 166, suggestion: "What is a software security test" },
  { id: 167, suggestion: "How to use Apache Avro" },
  { id: 168, suggestion: "Learn Lua for game scripting" },
  { id: 169, suggestion: "What is a software acceptance test" },
  { id: 170, suggestion: "How to use Apache Thrift" },
  { id: 171, suggestion: "What is a software regression test" },
  { id: 172, suggestion: "Learn Tcl for scripting" },
  { id: 173, suggestion: "How to use Apache Tika" },
  { id: 174, suggestion: "What is a software exploratory test" },
  { id: 175, suggestion: "How to use Apache Mahout" },
  { id: 176, suggestion: "Learn AWK for text processing" },
  { id: 177, suggestion: "What is a software load test" },
  { id: 178, suggestion: "How to use Apache Giraph" },
  { id: 179, suggestion: "What is a software stress test" },
  { id: 180, suggestion: "Learn Sed for text processing" },
  { id: 181, suggestion: "How to use Apache Helix" },
  { id: 182, suggestion: "What is a software endurance test" },
  { id: 183, suggestion: "How to use Apache Kylin" },
  { id: 184, suggestion: "Learn Prolog for logic programming" },
  { id: 185, suggestion: "What is a software volume test" },
  { id: 186, suggestion: "How to use Apache Ambari" },
  { id: 187, suggestion: "What is a software localization test" },
  { id: 188, suggestion: "Learn Mercury for logic programming" },
  { id: 189, suggestion: "How to use Apache Ranger" },
  { id: 190, suggestion: "What is a software globalization test" },
  { id: 191, suggestion: "How to use Apache Atlas" },
  { id: 192, suggestion: "Learn Eiffel programming basics" },
  { id: 193, suggestion: "What is a software compliance test" },
  { id: 194, suggestion: "How to use Apache Knox" },
  { id: 195, suggestion: "What is a software accessibility test" },
  { id: 196, suggestion: "Learn Smalltalk programming basics" },
  { id: 197, suggestion: "How to use Apache Oozie" },
  { id: 198, suggestion: "What is a software penetration test" },
  { id: 199, suggestion: "How to use Apache Slider" },
  { id: 200, suggestion: "Learn Modula-2 programming basics" },
  { id: 201, suggestion: "What is a software recovery test" },
  { id: 202, suggestion: "How to use Apache Samza" },
  { id: 203, suggestion: "What is a software failover test" },
  { id: 204, suggestion: "Learn Simula programming basics" },
  { id: 205, suggestion: "How to use Apache Apex" },
  { id: 206, suggestion: "What is a software disaster recovery test" },
  { id: 207, suggestion: "How to use Apache Trafodion" },
  { id: 208, suggestion: "Learn Algol programming basics" },
  { id: 209, suggestion: "What is a software migration test" },
  { id: 210, suggestion: "How to use Apache Calcite" },
  { id: 211, suggestion: "What is a software integration test" },
  { id: 212, suggestion: "Learn PL/I programming basics" },
  { id: 213, suggestion: "How to use Apache DataFu" },
  { id: 214, suggestion: "What is a software unit test" },
  { id: 215, suggestion: "How to use Apache Crunch" },
  { id: 216, suggestion: "Learn ML programming basics" },
  { id: 217, suggestion: "What is a software system test" },
  { id: 218, suggestion: "How to use Apache Pig" },
  { id: 219, suggestion: "What is a software alpha test" },
  { id: 220, suggestion: "Learn Dylan programming basics" },
  { id: 221, suggestion: "How to use Apache Hive" },
  { id: 222, suggestion: "What is a software beta test" },
  { id: 223, suggestion: "How to use Apache Spark SQL" },
  { id: 224, suggestion: "Learn Icon programming basics" },
  { id: 225, suggestion: "What is a software gamma test" },
  { id: 226, suggestion: "How to use Apache Hadoop YARN" },
  { id: 227, suggestion: "What is a software delta test" },
  { id: 228, suggestion: "Learn Rexx programming basics" },
  { id: 229, suggestion: "How to use Apache Hadoop MapReduce" },
  { id: 230, suggestion: "What is a software epsilon test" },
  { id: 231, suggestion: "How to use Apache Hadoop HDFS" },
  { id: 232, suggestion: "Learn CLIPS for expert systems" },
  { id: 233, suggestion: "What is a software zeta test" },
  { id: 234, suggestion: "How to use Apache Hadoop Common" },
  { id: 235, suggestion: "What is a software eta test" },
  { id: 236, suggestion: "Learn Scheme programming basics" },
  { id: 237, suggestion: "How to use Apache Hadoop Ozone" },
  { id: 238, suggestion: "What is a software theta test" },
  { id: 239, suggestion: "How to use Apache Hadoop Submarine" },
  { id: 240, suggestion: "Learn Lisp programming basics" },
  { id: 241, suggestion: "What is a software iota test" },
  { id: 242, suggestion: "How to use Apache Hadoop Rumen" },
  { id: 243, suggestion: "What is a software kappa test" },
  { id: 244, suggestion: "Learn Logo programming basics" },
  { id: 245, suggestion: "How to use Apache Hadoop Gridmix" },
  { id: 246, suggestion: "What is a software lambda test" },
  { id: 247, suggestion: "How to use Apache Hadoop DistCp" },
  { id: 248, suggestion: "Learn Scratch for kids programming" },
  { id: 249, suggestion: "What is a software mu test" },
  { id: 250, suggestion: "How to use Apache Hadoop S3Guard" },
  { id: 251, suggestion: "What is a software nu test" },
  { id: 252, suggestion: "Learn Blockly for visual programming" },
  { id: 253, suggestion: "How to use Apache Hadoop ViewFS" },
  { id: 254, suggestion: "What is a software xi test" },
  { id: 255, suggestion: "How to use Apache Hadoop WebHDFS" },
  { id: 256, suggestion: "Learn Alice for storytelling programming" },
  { id: 257, suggestion: "What is a software omicron test" },
  { id: 258, suggestion: "How to use Apache Hadoop HttpFS" },
  { id: 259, suggestion: "What is a software pi test" },
  { id: 260, suggestion: "Learn Turing programming basics" },
  { id: 261, suggestion: "How to use Apache Hadoop KMS" },
  { id: 262, suggestion: "What is a software rho test" },
  { id: 263, suggestion: "How to use Apache Hadoop Balancer" },
  { id: 264, suggestion: "Learn Pascal programming basics" },
  { id: 265, suggestion: "What is a software sigma test" },
  { id: 266, suggestion: "How to use Apache Hadoop FSCK" },
  { id: 267, suggestion: "What is a software tau test" },
  { id: 268, suggestion: "Learn BASIC programming basics" },
  { id: 269, suggestion: "How to use Apache Hadoop Shell" },
  { id: 270, suggestion: "What is a software upsilon test" },
  { id: 271, suggestion: "How to use Apache Hadoop CLI" },
  { id: 272, suggestion: "Learn Assembly programming basics" },
  { id: 273, suggestion: "What is a software phi test" },
  { id: 274, suggestion: "How to use Apache Hadoop Metrics" },
  { id: 275, suggestion: "What is a software chi test" },
  { id: 276, suggestion: "Learn COBOL programming basics" },
  { id: 277, suggestion: "How to use Apache Hadoop Logs" },
  { id: 278, suggestion: "What is a software psi test" },
  { id: 279, suggestion: "How to use Apache Hadoop Audit" },
  { id: 280, suggestion: "Learn RPG programming basics" },
  { id: 281, suggestion: "What is a software omega test" },
  { id: 282, suggestion: "How to use Apache Hadoop Security" },
  { id: 283, suggestion: "What is a software alpha-beta test" },
  { id: 284, suggestion: "Learn APL programming basics" },
  { id: 285, suggestion: "How to use Apache Hadoop Federation" },
  { id: 286, suggestion: "What is a software gamma-delta test" },
  { id: 287, suggestion: "How to use Apache Hadoop Quota" },
  { id: 288, suggestion: "Learn J programming basics" },
  { id: 289, suggestion: "What is a software epsilon-zeta test" },
  { id: 290, suggestion: "How to use Apache Hadoop Snapshot" },
  { id: 291, suggestion: "What is a software eta-theta test" },
  { id: 292, suggestion: "Learn K programming basics" },
  { id: 293, suggestion: "How to use Apache Hadoop Trash" },
  { id: 294, suggestion: "What is a software iota-kappa test" },
  { id: 295, suggestion: "How to use Apache Hadoop Archive" },
  { id: 296, suggestion: "Learn Q programming basics" },
  { id: 297, suggestion: "What is a software lambda-mu test" },
  { id: 298, suggestion: "How to use Apache Hadoop Erasure Coding" },
  { id: 299, suggestion: "What is a software nu-xi test" },
  { id: 300, suggestion: "How to use Apache Hadoop Encryption" },
];

export default searchSuggestions;
